file_format: "1"
id: hrkzod
name: hrkzod
type: shield
url: https://www.splitlogic.xyz/buildguides/hrkzod-build-guide
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - encoder
siblings:
  - hrkzod_left
  - hrkzod_right
